### ISSUE TITLE
Ignore {:error, :obscured} ?

### ISSUE THREAD

**Issue by brandonparsons** [keathley/wallaby#373] opened 2018-06-07 03:27 UTC
I'm using Wallaby `0.20.0`.

I have started getting a pile of `{:error, :obscured}` failures in my feature tests. These used to pass, but have started failing for cases where I'm trying to interact with an element in a modal popup.

I'm not sure why Wallaby thinks these are obscured (I've taken screenshots and the fields are there). Is there any way to tell Wallaby to go ahead and interact with elements it believes are obscured (without failing)?

**Comment by keathley** [comment] 2018-06-07 18:47
I'll look through the changelog to see if there's anything specific that would have caused this. could you give me a sample test? That way I can bisect and see whats going on?

**Comment by brandonparsons** [comment] 2018-06-09 14:32
Unfortunately I'm not going to be able to pin down for you exactly when this error would have started showing up (i.e. it's not a result of `0.19` -> `0.20`).

Development of our app slowed way down when we went to focus on usage growth -- I haven't been running a lot of feature tests recently. Also, I have it set up to specifically require that I run feature tests (not on `mix test`), so previous usage was also spotty.

I do know for a fact though that the tests have not always been failing.

I'm not sure how you would go about replicating, but here is an example failing test:

```elixir
  @tag :feature
  test "can add activities, items are reflected in the daily log", %{session: session} do
    quick_login(session)
    assert_on(session, @dashboard_path)

    session
    |> click(@add_item_dashboard_button)
    |> find(Query.css(".modal.visible"))
    |> click(Query.css("[data-test-add-activity-link]"))

    # Make sure page transition done
    find(session, Query.css(~s|form[action="/activities"]|))
    assert Browser.has_text?(session, "[Infant Room (Little Bears Daycare): Billy Smith]")

    # <------------- This is where the test will fail (the `fill_in` `activity_details` part). I have taken a screenshot here, and validated that the text field is in fact on the page.
    session
    |> fill_in(Query.text_field("activity_details"), with: "Played in the snow!")
    |> fill_in_semantic_ui_time_field("activity_display_time", "8:15AM")
    |> click(@submit_button)

    assert_flash(session, "Activity recorded!")

    # Double check the activity was created
    visit(session, daily_report_path(@endpoint, :program, display: %{program_id: @program_id}))
    assert Browser.has_text?(session, "Daily Activity Log")
    assert Browser.has_text?(session, "Played in the snow!")
  end
```

If it's not immediately obvious what the issue is, is there an quick way to set a config flag that allows interaction with obscured elements?

**Comment by keathley** [comment] 2018-06-12 14:08
Is the page rendered with JS? Does it have any sort of fancy css? What browser are you using?

**Comment by keathley** [comment] 2018-06-13 18:30
Just a thought, but it may be that we aren't retrying correctly if we get the obscured element error. I'll have to look through the code to see if thats the case though.

**Comment by brandonparsons** [comment] 2018-06-14 13:37
@keathley Thanks! Let me know if you find anything. I promise you the field is there and can be interacted with in a real browser. I'd like to keep feature tests around, so anything you can come up with would be greatly appreciated.

**Comment by keathley** [comment] 2018-06-14 13:49
I suspect it has something to do with when chrome driver is attempting to interact with the modal combined with how the modal is opening. It may be something that we aren't handling correctly internally. I'll try to dig around.

**Comment by thmzlt** [comment] 2018-06-28 21:29
I'm also getting this error when trying to manipulate a page with zero javascript using `chromedriver`. Let me know how I can help.

**Comment by evax** [comment] 2018-06-29 05:56
I've been seeing the same thing with chromedriver for elements that are out of the current viewport, and work around it explicitly scrolling the element into view before interacting with it.

**Comment by keathley** [comment] 2018-07-02 14:51
@evax what are you doing to scroll the element into view?

**Comment by evax** [comment] 2018-07-02 15:46
@keathley I'm calling javascript for now

```elixir
def scroll_into_view(session, selector) do
    session
    |> Wallaby.Browser.execute_script("""
      $("#{selector}")[0].scrollIntoView();
      """)
end
```

**Comment by keathley** [comment] 2018-07-10 17:48
@evax, @thmzlt can either of you provide a failing test case so I can reproduce this locally?

**Comment by mhanberg** [comment] 2018-10-30 03:08
This might be able to be closed due to #389.

**Comment by keathley** [comment] 2018-10-31 13:08
@brandonparsons Would you mind testing on master to see if this has solved your problem?

**Comment by brandonparsons** [comment] 2018-10-31 14:07
I'll give it a shot today. I'm not positive all my feature tests will still
work (I've let them slide due to false negatives), but if most of them pass
that would probably be indicative of the problem being fixed.

**Comment by brandonparsons** [comment] 2018-10-31 18:06
@keathley I'm getting the same number of test failures, but a different failure message that may be more helpful.

```
** (CaseClauseError) no case clause matching: {:error, "unknown error: call function result missing 'value'\n  (Session info: headless chrome=70.0.3538.77)\n  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.6 x86_64)"}
     code: |> fill_in(Query.text_field("account_contact_email"), with: "new-contact-email@example.com")
```

I don't know what to do with this, but perhaps it helps you?

**Comment by keathley** [comment] 2018-10-31 18:16
Thanks @brandonparsons this is definitely a lot more helpful

**Comment by mhanberg** [comment] 2018-10-31 18:59
@brandonparsons what version of Chrome and ChromeDriver are you using?

**Comment by brandonparsons** [comment] 2018-10-31 21:17
@mhanberg I can't check right now, but is that not it right in the error message?

`(Session info: headless chrome=70.0.3538.77)\n  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.6 x86_64)`

**Comment by mhanberg** [comment] 2018-10-31 21:52
😅 I need to learn to read. Thanks. Could you try updating chromedriver? I believe that the current version is `2.43`. 

At some point, chromedriver moved from `brew` to `brew cask`, so you may need to run `brew uninstall chromdriver` and `brew cask install chromedriver`.

@brandonparsons 

thanks

**Comment by keathley** [comment] 2018-11-01 00:54
I have a suspicion that something in chromedriver has changed and our internal contract has broken. Its probably something we need to investigate further.

**Comment by brandonparsons** [comment] 2018-11-01 03:17
@mhanberg @keathley Upgrading chromedriver actually seemed to really help. Went from 14 failures to 2, and those two could actually be legitimate failures given that I haven't been taking very good care of my feature tests!

**Comment by keathley** [comment] 2018-11-01 12:59
Awesome! Sorry it caused you some pain but glad to hear that it's working now. We'll go ahead and close this for now but if you encounter more issues let us know 👍

**Closed by keathley** 2018-11-01 12:59 UTC
Labels: Kind:Bug, Level:Intermediate
