### ISSUE TITLE
Intermittent text errors with fill_in

### ISSUE THREAD

**Issue by jpettit** [keathley/wallaby#122] opened 2016-12-14 23:31 UTC
Currently seeing errant behavior with fill_in where the static text being passed to fill_in is dropping characters.

An Example
```
session
  |> visit("/")
  |> find("#myFormId")
  |> fill_in("formFieldA", with: "SomeInputTextThatIWant")
  |> fill_In("formFieldB", with: "TheTextForFieldB")
  |> click_on("formSubmit")

result = session
  |> find(".state-change")
  |> text

assert result == "I expect to see this"
```

In the rudimentary example above, I'm seeing the second find for the state change fail (the form was not submitted), and when I look at the screenshot, I'm seeing (intermittent and random) characters missing from the two form fields I'm writing to with fill_in.

Is anyone else seeing any such issues?

*EDIT 12/15/2016*
The issue is as a result of the form failing to submit due to validation constraints.  The `find(".state-change")` is actually appropriately failing because the state change never occurs due to the original `fill_in()/2` helper failing to put in my specific text from a string literal.  So, the attempt at finding the state change is irrelevant.

**Comment by keathley** [comment] 2016-12-14 23:42
@jpettit Can you re-create a demo of the failure? I'll be happy to take a look at it. Some other thoughts. Is this just a basic form? Are there any Javascript interactions with the form? Are you sending special characters of any kind?

**Comment by jpettit** [comment] 2016-12-15 22:25
@keathley No special characters.  Characters are just dropped (and it seems random).  The input form is defined with `action=javascript::void(0);`.  The input fields have the following attributes: `autocomplete id name class autofocus type style`

I am using v0.15.0 - despite the docs stating v0.14.0.  Let me try v14.

**Comment by jpettit** [comment] 2016-12-15 23:22
I did some more experimentation and I'm finding that I'm only seeing the `fill_in/2` helper from the example above really only input the correct text maybe 1 out of 10 times.  

I added the following to replace the second session statements:  
`assert find(session, "#formFieldA")     |> has_value?("SomeInputTextThatIWant")`

**Comment by jpettit** [comment] 2016-12-16 00:29
Another update - I've installed and configured Hound with phantomjs and the same issue occurs using their library.  So this is probably an issue with phantomjs, and a troubling one considering Wallaby does not support selenium or chromedriver

**Comment by keathley** [comment] 2016-12-16 04:52
Based on what you're describing it sounds like it might be an issue with the site you're trying to test. Not being able to fill in form fields is probably something that would get reported pretty quickly after all 😄. 

I want to help solve this issue but currently I don't have a lot to go on. Even a gist of the html and relevant js would be helpful. Can you double check the version of phantom you're running? Can you give me a specific example of text you're trying to submit? The more information the better.

**Comment by keathley** [comment] 2017-02-09 19:02
Since I'm not really sure how to reproduce this I'm going to close this issue for now. If you have some more info then feel free to re-open it.

**Closed by keathley** 2017-02-09 19:02 UTC
