### ISSUE TITLE
wallaby does not work with the latest version of chromedriver

### ISSUE THREAD

**Issue by ayrat555** [keathley/wallaby#432] opened 2019-06-10 08:40 UTC
## Issue

Wallaby fails on our ci with chromedriver `75.0.3770.8`. Everything's ok with `74.0.3729.6`

**Comment by mhanberg** [comment] 2019-06-10 12:04
Could you add some more specifics about what is not working?

I ran into this yesterday but hadn't been able to find the cause yet.

Thanks for the report.

As for me, I Wallaby is not able to click links or buttons, but doesn't fail the test, it just moves forward until a line that runs an assertion.

**Comment by mhanberg** [comment] 2019-06-10 12:36
This is the response I'm seeing from chromedriver when sending the click event

```
%{
  "value" => %{
    "error" => "invalid argument",
    "message" => "invalid argument: missing command parameters",
    "stacktrace" => "0   chromedriver                        0x000000010b6eb8e9 chromedriver + 3594473\n1   chromedriver                        0x000000010b67b543 chromedriver + 3134787\n2   chromedriver                        0x000000010b42729f chromedriver + 692895\n3   chromedriver                        0x000000010b3b944d chromedriver + 242765\n4   chromedriver                        0x000000010b3b8fa4 chromedriver + 241572\n5   chromedriver                        0x000000010b3829a9 chromedriver + 18857\n6   chromedriver                        0x000000010b6aa555 chromedriver + 3327317\n7   chromedriver                        0x000000010b6b5e60 chromedriver + 3374688\n8   chromedriver                        0x000000010b6b5bf8 chromedriver + 3374072\n9   chromedriver                        0x000000010b689d39 chromedriver + 3194169\n10  chromedriver                        0x000000010b6b66d8 chromedriver + 3376856\n11  chromedriver                        0x000000010b69df27 chromedriver + 3276583\n12  chromedriver                        0x000000010b380c8e chromedriver + 11406\n13  libdyld.dylib                       0x00007fff70f093d5 start + 1\n"
  }
}
```

**Comment by michallepicki** [comment] 2019-06-10 12:37
Hi! I'm working with Wallaby using Selenium and looks like I can shed some light on this issue:

Looking at the chromedriver [Downloads](http://chromedriver.chromium.org/downloads) page, under ChromeDriver 75 there's a note:
> The most noticeable change is ChromeDriver now runs in W3C standard compliant mode by default

Currently, the Wallaby WebDriver client uses the old Selenium WebDriver protocol for most of the commands (documented [here](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol)), with a few exceptions where new functionality was added using new W3C protocol (documented [here](https://w3c.github.io/webdriver/)). So far ChromeDriver was using the old protocol, while supporting commands from the new protocol. Looks like it changed now.

Some commands are probably working fine with ChromeDriver 75 because the new W3C protocol was based on the Selenium WebDriver.

The solution would be to find out if there's a way to connect to ChromeDriver 75 using the old "legacy" protocol, and make it the default option for ChromeDriver backend in Wallaby for now. Eventually we'll need to implement a client for the new protocol, if not for ChromeDriver then for Selenium, as e.g. Safari 12 is supporting it exclusively and deprecated the old protocol and next browsers will likely follow.

**Comment by mhanberg** [comment] 2019-06-10 12:42
Good catch, I spent some time looking for the changelog and it didn't cross my mind to check the downloads page 😅 🤦‍♂ .

I agree. 

I would say the immediate workaround is to downgrade your chromedriver to v74, pending more permanent fixes.

**Comment by mhanberg** [comment] 2019-06-10 23:42
I was able to fix my capybara setup at work by passing `w3c: false` in the `chromeOptions`, but I haven't had success getting that to work with Wallaby yet.

**Comment by VEkh** [comment] 2019-06-12 20:06
I also had the same issue and downgrading worked. This, however, can't be a good long term solution.

**Comment by keathley** [comment] 2019-06-13 17:37
@VEkh I dont' think anyone is suggesting downgrading as the final solution.

**Comment by jc00ke** [comment] 2019-06-13 21:26
I'm using Heroku CI with the [chromedriver buildpack](https://github.com/heroku/heroku-buildpack-chromedriver) and setting `CHROMEDRIVER_VERSION="74.0.3729.6"` did the trick for me.

**Comment by rickclare** [comment] 2019-06-14 11:42
Chromedriver has now been updated to **v75.0.3770.90**
https://sites.google.com/a/chromium.org/chromedriver                                                                                                                                       

Upgrading my local Chromedriver from v75.0.3770.8 to v75.0.3770.90 seems to have fixed the issue for me.

Perhaps one of the issues listed as fixed here has resolved the problem?
https://chromedriver.storage.googleapis.com/75.0.3770.90/notes.txt

**Comment by mhanberg** [comment] 2019-06-14 11:46
Are you meaning that Wallaby works out of the box with v75.0.3770.90 or it works when passing `w3c:false` in the chrome options?

Either way this is promising and explains why I thought I was going crazy, thanks for the update!

**Comment by rickclare** [comment] 2019-06-14 11:52
Hi @mhanberg,  to clarify, my tests were failing under Chromedriver v75.0.3770.8, but are now passing under Chromedriver v75.0.3770.90   I didn't pass any chrome-options or modify the Wallaby source-code.

**Comment by mhanberg** [comment] 2019-06-14 11:59
@rickclare ok, thanks. 

I can also confirm that by only clicking “rebuild” on CI, my test sweet is also now passing!

I am confused as to why tho, because the changelog still says that it should be running in w3c compliant mode by default. ¯\_(ツ)_/¯

**Comment by rickclare** [comment] 2019-06-14 12:25
Looks like the upgrade from .8 to .90 contained only the following changes:

> * Fixed a bug that incorrectly rejected POST requests with empty body in OSS mode
> * Added new endpoints for retrieving Chrome log

https://groups.google.com/forum/#!searchin/chromedriver-users/ChromeDriver$2075.0.3770.90%7Csort:date/chromedriver-users/OiwvmaPbLAs/nlib05UYAgAJ

**Comment by mhanberg** [comment] 2019-06-14 13:57
This was the line that I found the most promising: 

>Resolved issue 2943: goog:chromeOptions.w3c=false doesn't work for POST request with empty body [Pri-1]

it's interesting that it still works without passing `w3c: false`.

**Comment by jc00ke** [comment] 2019-06-14 15:06
Maybe `LATEST` wasn't updated in the chromedriver index, but after specifying `75.0.3770.90`, my tests started to pass again. `.90++`

**Comment by mhanberg** [comment] 2019-06-14 16:29
@jc00ke This is the way CircleCI installs chrome and chromedriver. (just an FYI, not sure what CI setup you are using)

**Comment by jc00ke** [comment] 2019-06-14 16:33
@mhanberg [I'm on HerokuCI](#issuecomment-501885100) where the buildpack gives me some flexibility on what version I want to install.

**Comment by mhanberg** [comment] 2019-07-14 16:50
Closing this issue as it seems to have worked itself out.

It looks like we should eventually look at creating a client for the newer w3c protocl.

**Closed by mhanberg** 2019-07-14 16:50 UTC
Labels: Kind:Bug, Level:Advanced
