### ISSUE TITLE
Stale reference

### ISSUE THREAD

**Issue by Slowbad** [keathley/wallaby#114] opened 2016-10-29 22:36 UTC
I'm trying to use Wallaby to scrape event information from the Wizards of the Coast event locator. The locator is written entirely in javascript and I'm getting what looks to be something about stale elements. The code I've written (see below) will sometimes come back properly but more often than not I get the error at the bottom of issue. 

Example url: http://locator.wizards.com/#brand=magic&a=location&p=27410&et=PPTQ&sd=10.30.2016&ed=11.01.2016&massmarket=no&loc=329977&orgid=8514&addrid=329977

```
@event_name "Magic Preliminary Pro Tour Qualifier"

def get_store_events(url) do
  {:ok, session} = Wallaby.start_session

events = session
 |> visit(url)
 |> click_element("#event-types-list-magic li a", text: @event_name)
 |> find("#event-table-content")
 |> all("dl.even, dl.odd")
 |> Enum.map(fn node ->
   %{
     date: find(node, ".date") |> text,
     event_title: find(node, ".event-title") |> text,
     store_address: find(node, ".event-address") |> text,
     format: find(node, ".event-legacy") |> text,
     store_telephone: find(node, ".event-tel") |> text,
     info: find(node, ".event-mail") |> text
   }
 end)

 Wallaby.end_session(session)

 events
end


   def click_element(session, selector, opts \\ []) do
     find(session, selector, opts)
     |> click()
     session
   end
```

*\* (FunctionClauseError) no function clause matching in Kernel.=~/2
     (elixir) lib/kernel.ex:1510: Kernel.=~(%{"class" => "org.openqa.selenium.StaleElementReferenceException", "message" => "{\"errorMessage\":\"Element is no longer attached to the DOM\",\"request\":{\"headers\":{\"Content-Type\":\"text/json\",\"Host\":\"localhost:42119\",\"User-Agent\":\"hackney/1.6.1\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"text\",\"directory\":\"/\",\"path\":\"/text\",\"relative\":\"/text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/text\",\"queryKey\":{},\"chunks\":[\"text\"]},\"urlOriginal\":\"/session/1b427410-9e24-11e6-9413-7d6ac7c1afaa/element/:wdc:1477778862223/text\"}}", "screen" => "large pile of what looked to be base 64"}, ~r/Magic\ Preliminary\ Pro\ Tour\ Qualifier/)
     (elixir) lib/enum.ex:787: anonymous fn/3 in Enum.filter/2
     (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
     (elixir) lib/enum.ex:787: Enum.filter/2
    (wallaby) lib/wallaby/node/query.ex:336: Wallaby.Node.Query.assert_text/1
    (wallaby) lib/wallaby/node/query.ex:276: anonymous fn/1 in Wallaby.Node.Query.find_element/3
    (wallaby) lib/wallaby/node/query.ex:383: Wallaby.Node.Query.retry/2
    (wallaby) lib/wallaby/node/query.ex:113: Wallaby.Node.Query.find/3

I'm not sure how to get around this issue with the stale elements. Increased wait time or something else?

**Comment by keathley** [comment] 2016-11-12 03:23
So it looks like whats happening is that the `click_element("#event-types-list-magic li a", text: @event_name)` action is failing. Here's whats happening. The `find` command first finds all DOM nodes that match the `#event-types-list-magic li a` selector. Once it has those dom nodes it validates the other options. In this case the node has to include the text "Magic Preliminary Pro Tour Qualifier". Checking the text requires n additional queries to webdriver (1 for each node). The issue is that in between finding all of the dom nodes that match the selector, and checking those dom nodes for matching text, one of the nodes is being removed from the dom. This results in the unhandled stale node error.

**Comment by tiodan81** [comment] 2016-11-23 19:05
We're hitting this as well, I believe that capybara handles this by rerunning the query rather than failing outright. This is a very common issue on single page apps where the dom changes in response to route changes. It leaves us with no real way to check that the page has actually changed.

Consider the example of signing in and then verifying that we are signed in by looking for a sign out button. When we look for the sign out button, we get the sign in button while it is signing in but then it is immediately taken off of the dom and replaced with a sign out button. This, more often than not, causes the same exception OP is seeing.

**Comment by keathley** [comment] 2017-02-17 19:46
The issue was that the internal retry logic was throwing an unhandled `StaleReferenceException`. That retry logic has been updated to better handle this case with the other api refactors that are in master. @Slowbad I'm not sure if this is still relevant to you but if you would like to try this against master it may fix your issue. All the changes will be in the next release.

I'm going to close this for now but if the issue persists then please re-open.

**Closed by keathley** 2017-02-17 19:46 UTC
