### ISSUE TITLE
`click_link` does not work with `method: :delete` links

### ISSUE THREAD

**Issue by fredwu** [keathley/wallaby#67] opened 2016-07-09 09:22 UTC
Hi,

I am trying to use Wallaby to test the user session flow, it's a Phoenix app. So for the sign out, the EEx looks like this:

``` EEx
<%= link "Sign Out", to: session_path(@conn, :delete), method: :delete %>
```

Unfortunately this doesn't appear to work. Use `take_screenshot` I can see that the link is not getting clicked.

If I change the implementation to either:

``` EEx
<%= form_tag session_path(@conn, :delete), method: :delete %>
  <%= submit "Sign Out", class: "btn btn-primary" %>
</form>

# use `click_on` in the test
```

Or:

``` EEx
<%= link "Sign Out", to: session_path(@conn, :delete) %>

# change route from :delete to :get
```

Then the test works.

Also, the Phoenix JS is included correctly, and JS is being executed in the test environment.

Is this a known issue, or have I somehow done this incorrectly?

**Comment by fredwu** [comment] 2016-07-09 10:31
After some investigation this appears to be a phantomjs limitation...

Poltergeist seems to be getting around the issue by lots of [custom JS](https://github.com/teampoltergeist/poltergeist/blob/6fb4c31efa62add0eec1bf20fe658da5ead10937/lib/capybara/poltergeist/client/browser.coffee#L280-L302).

Closing this for now.

**Comment by keathley** [comment] 2016-07-10 03:32
@fredwu Do you know if this is because of an issue with the phoenix javascript and phantom? Or is it just one of the many other issues in phantom ;)

I know that we can't currently support alert interactions which may be causing issues.

**Comment by fredwu** [comment] 2016-07-10 04:40
Seems to be the (in)ability for Phantomjs to handle the click event: http://stackoverflow.com/questions/15739263/phantomjs-click-an-element

Phoenix HTML's relevant snippet:

```js
window.addEventListener('click', function (event) {
  if(event.target && event.target.matches('a[data-submit=parent]')) {
    var message = event.target.getAttribute('data-confirm');
    if (message === null || confirm(message)) {
      event.target.parentNode.submit();
    };
    event.preventDefault();
    return false;
  }
}, false);
```

**Comment by keathley** [comment] 2016-07-10 15:22
I'll test some more. Its possible that we can create a work around for phantom.

**Comment by Thau** [comment] 2016-07-12 08:02
I sent a pull request with a workaround to fix this issue. It's rough, so please test it first :).

**Comment by lukerollans** [comment] 2016-07-26 13:18
I came across this issue previously myself and learned that it was indeed a limitation of Phantom, so I went another route to ensure test coverage. I would love to go back to a `DELETE` link.

**Comment by keathley** [comment] 2016-07-26 20:16
Thanks for working on this @Thau! This has been fixed upstream in phoenix. This issue should be resolved if you update phoenix_html to 2.6.2.

**Comment by lukerollans** [comment] 2016-07-27 02:36
Confirming! 🎉

**Comment by Thau** [comment] 2016-07-27 07:09
Also confirming. This is great :)

**Comment by fredwu** [comment] 2016-07-27 07:45
Interesting, did you have to adjust anything else other than the `phoenix_html` dependency upgrade? It's still breaking for me for some reason... 😂

**Comment by lukerollans** [comment] 2016-07-27 08:30
@fredwu Nope, just made sure `phoenix_html` was up to date!

**Comment by fredwu** [comment] 2016-07-28 00:20
@lukerollans Thanks! It turned out to be `node_modules`... :trollface:

**Comment by bitboxer** [comment] 2017-03-07 22:03
Sadly i have problems with this on, details [on elixirforum](https://elixirforum.com/t/problems-with-wallaby-and-delete-links-on-travis/4019). Maybe someone here can help me?

**Comment by keathley** [comment] 2017-03-08 14:58
@bitboxer what version of phoenix are you running?

**Comment by bitboxer** [comment] 2017-03-08 15:01
I am running 1.2.1. But I am an elixir beginner. Could be that I am doing something wrong here. The strange thing is that it works locally, but not on travis. You can see what I did [in this repo](https://github.com/signdict/website/tree/user-login) and the feature test is [here](https://github.com/signdict/website/blob/user-login/test/features/user_sign_up_test.exs).

Thank you for looking into this.

**Comment by keathley** [comment] 2017-03-08 15:56
Thanks, I'll check out that repo when I get a chance.

**Comment by keathley** [comment] 2017-03-08 16:19
@bitboxer Just tried running the tests. Removed the commented out assertion and everything is working for me. One possible issue is that your JS is taking a while to execute and exceeding the wallaby timeout. You could try increasing it with the `max_wait_time` config option. The default is 3 seconds.

**Comment by bitboxer** [comment] 2017-03-08 21:20
Yes, it is working for me locale, too. Will check tomorrow on travis with increased timeout. Thanks for your time!  Will update after I have tried it.

**Comment by bitboxer** [comment] 2017-03-08 21:40
Okay, found some time to do it tonight :wink:

Sadly even when increasing it to 30 seconds it does not work on travis. It just fails because of a postgres timeout after 15 seconds. 

```
...21:35:59.547 [error] Postgrex.Protocol (#PID<0.686.0>) disconnected: ** (DBConnection.ConnectionError) owner #PID<0.883.0> timed out because it owned the connection for longer than 15000ms

  1) test sign up user, login and logout (SignDict.UserSignUpTest)

     test/features/user_sign_up_test.exs:4

     ** (Wallaby.QueryError) Expected to find 1, visible element that matched the css '.alert-info' but 0, visible elements were found.

     

     stacktrace:

       (wallaby) lib/wallaby/browser.ex:783: Wallaby.Browser.find/2

       (wallaby) lib/wallaby/browser.ex:750: Wallaby.Browser.find/3

       test/features/user_sign_up_test.exs:31: (test)

...................................
```

Really weird that it does not work on travis, but locally is fine. Does anyone here have a project that uses the delete link on travis?

**Comment by PragTob** [comment] 2017-03-09 09:05
Are you 100% sure travis is running the same phantomJS version? E.g. just ahd a brief look at the setup, what I do in our project is put phantomJS as part of the dependencies and then point the wallaby path to `node_modules/phantomjs-prebuilt/bin/phantomjs` this way I can be really sure it does the same thing :D 

Plus I tried replicating yesterday a bit as well. The weird thing for me was _the first time_ I ran the tests the test failed, but it passed every time after that. So, maybe weird coincidence maybe something else weird.

**Comment by bitboxer** [comment] 2017-03-09 11:04
I am not 100% sure. I added a new phantomjs during the setup phase in travis. It outputs correctly. But I haven't set the phantomjs location, I just prepended the path. Will try to set  the path in the wallaby configuration after lunch

**Comment by bitboxer** [comment] 2017-03-09 13:11
Okay, now I am 100% sure. The phantomjs is now added to the wallaby config and I am installing the same version I am using locally:

<img width="439" alt="screen shot 2017-03-09 at 14 05 32" src="https://cloud.githubusercontent.com/assets/56195/23751415/9698dcbc-04d1-11e7-870e-d731facad769.png">

And sadly it fails. I will try to investigate a bit more with a debian vm tomorrow that replicates the travis build environment.

**Comment by keathley** [comment] 2017-03-22 16:04
@bitboxer did you find a fix for this?

**Comment by bitboxer** [comment] 2017-03-22 16:17
Oh, sorry. Didn't update here. I tried to replicate it on a VM that is close to travis, but I failed 😭 . So no, haven't found a fix yet

**Comment by bitboxer** [comment] 2017-03-22 16:18
But it is still on my todo list. Will continue to investigate it every other week or so

**Comment by keathley** [comment] 2017-03-22 17:08
Sounds good. I'm going to close this for now since I'm not sure how to reproduce the issue that you're seeing. If you figure something out feel free to re-open or create a new issue.

**Closed by keathley** 2017-03-22 17:08 UTC
