### ISSUE TITLE
"PhantomJS has crashed" -- for any url

### ISSUE THREAD

**Issue by GildedHonour** [keathley/wallaby#265] opened 2017-06-16 16:26 UTC
Code:
```

    {:ok, session} = Wallaby.start_session()
    visit(session, "http://any url ......")

```

Error:
```

PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
/usr/bin/sh: line 13: kill: (22485) - No such process
/usr/bin/sh: line 10: 22485 Segmentation fault      (core dumped) "$@"

=INFO REPORT==== 17-Jun-2017::00:22:34 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application scraper_test: exited in: MyApp.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{id: nil, reason: :econnrefused}}
            (wallaby) lib/wallaby/phantom/driver.ex:505: Wallaby.Phantom.Driver.check_logs!/2
            (wallaby) lib/wallaby/element.ex:48: Wallaby.Element.clear/1
            (wallaby) lib/wallaby/element.ex:66: Wallaby.Element.fill_in/2
            (wallaby) lib/wallaby/browser.ex:446: Wallaby.Browser.find/3
            (scraper_test) lib/scraper_test.ex:25: WallabyScraper.start/0
            (kernel) application_master.erl:273: :application_master.start_it_old/4
```

PhantomJS 2.1.1
geckodriver 0.16.1

**Comment by PragTob** [comment] 2017-06-16 16:41
Hm looks like phantom wasn't started correctly? Also looks a bit like it was using `sh` and not `bash` to run the script which might or might not be intended :thinking: 

are you running max or Linux?

I also run phantomjs 2.1.1 so it should work...

**Comment by GildedHonour** [comment] 2017-06-16 17:06
arch linux

**Comment by keathley** [comment] 2017-06-16 17:54
Is your phantom installed through npm or through something like pacman? Typically those sorts of errors. What is the specific url that you're trying to navigate to? My hunch is that this is a bug with phantom.

**Comment by PragTob** [comment] 2017-06-16 19:28
yeah maybe some sort of installation error... if you installed via npm/pacman maybe try the other route and try use the wallaby config for the phantom path to point to the correct one (I usually use the phantom package which is phantomjs-prebuilt or something)

**Comment by GildedHonour** [comment] 2017-06-17 01:03
installed by pacman
any url
no installation error

**Comment by keathley** [comment] 2017-06-17 02:19
Do you have any other configuration that would be important to see here? Can you run strace to see if its doing anything funky? Have you tried using phantom-prebuilt from npm? Let me know if you have any other input for reproducing this bug.

**Comment by keathley** [comment] 2017-07-17 23:40
I'm going to close this for now since I'm not sure how to reproduce it. If you manage to figure anything out feel free to re-open.

**Closed by keathley** 2017-07-17 23:40 UTC
