### ISSUE TITLE
Wallaby startup is crashing and error is vague

### ISSUE THREAD

**Issue by elbow-jason** [keathley/wallaby#354] opened 2018-03-12 16:31 UTC
This crash is preventing the app from starting up and the error message `{:error, {:crashed, 1}}` does not provided actionable information.

```
** (Mix) Could not start application wallaby: Wallaby.start(:normal, []) returned an error: shutdown: failed to start child: Wallaby.Phantom
    ** (EXIT) shutdown: failed to start child: Wallaby.ServerPool
        ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: {:error, {:crashed, 1}}
                (poolboy) src/poolboy.erl:275: :poolboy.new_worker/1
                (poolboy) src/poolboy.erl:296: :poolboy.prepopulate/3
                (poolboy) src/poolboy.erl:145: :poolboy.init/3
                (stdlib) gen_server.erl:365: :gen_server.init_it/2
                (stdlib) gen_server.erl:333: :gen_server.init_it/6
                (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
2018-03-12 07:50:00.384 [error] GenServer #PID<0.736.0> terminating
** (MatchError) no match of right hand side value: {:error, {:crashed, 1}}
    (poolboy) src/poolboy.erl:275: :poolboy.new_worker/1
    (poolboy) src/poolboy.erl:296: :poolboy.prepopulate/3
    (poolboy) src/poolboy.erl:145: :poolboy.init/3
    (stdlib) gen_server.erl:365: :gen_server.init_it/2
    (stdlib) gen_server.erl:333: :gen_server.init_it/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.735.0>, {{:badmatch, {:error, {:crashed, 1}}}, [{:poolboy, :new_worker, 1, [file: 'src/poolboy.erl', line: 275]}, {:poolboy, :prepopulate, 3, [file: 'src/poolboy.erl', line: 296]}, {:poolboy, :init, 3, [file: 'src/poolboy.erl', line: 145]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 365]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 333]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
```

This looks like it could be a poolboy issue, but I wanted to include Wallaby since the error is being caused through `Wallaby.start/2`

I have tried this on:

+ Elixir 1.5.2 and Elixir 1.6.2.
+ OTP 20.0.
+ Phantom 2.1.1 and 2.1.16.
+ Node 8.7.0.

We are using Wallaby `{:wallaby, "~> 0.19.2", only: :test}`. 

With the following in the `test_helper.exs`:

```
Application.put_env(:wallaby, :base_url, TheApp.Endpoint.url)
{:ok, _} = Application.ensure_all_started(:wallaby)
```

Any suggestions?

**Comment by PragTob** [comment] 2018-03-12 18:27
Wow that's rough :|

Of the top of my head, I have no idea - sorry but I'm also not that familiar with that part of the code base. I think one would need to debug into that place and see why/what crashes :( Hard to do without your app.

**Comment by keathley** [comment] 2018-03-12 18:38
@elbow-jason can you [enable sasl logs](https://hexdocs.pm/logger/Logger.html#module-error-logger-configuration) so we can get a better picture about whats going on?

**Comment by elbow-jason** [comment] 2018-03-13 16:52
@PragTob Honestly, even with the app it's hard. I've got at least 3 other dev's that have the same exact (AFAICT) versions of NodeJS, PhantomJS, Elixir, and Erlang; and they are not having any issues.

**Comment by elbow-jason** [comment] 2018-03-13 16:58
@keathley  Here is the error log with `handle_sasl_reports: true` in the `config/test.exs` of the project.
```
2018-03-13 09:51:55.691 [error] Process #PID<0.1150.0> terminating
** (exit) {:crashed, 1}
    (stdlib) gen_server.erl:349: :gen_server.init_it/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Initial Call: Wallaby.Phantom.Server.init/1
Ancestors: [#PID<0.1149.0>, Wallaby.ServerPool, Wallaby.Driver.Supervisor, Wallaby.Supervisor, #PID<0.1144.0>]
2018-03-13 09:51:55.696 [error] Process #PID<0.1148.0> terminating
** (MatchError) no match of right hand side value: {:error, {:crashed, 1}}
    (poolboy) src/poolboy.erl:275: :poolboy.new_worker/1
    (poolboy) src/poolboy.erl:296: :poolboy.prepopulate/3
    (poolboy) src/poolboy.erl:145: :poolboy.init/3
    (stdlib) gen_server.erl:365: :gen_server.init_it/2
    (stdlib) gen_server.erl:333: :gen_server.init_it/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Initial Call: :poolboy.init/1
Ancestors: [Wallaby.Driver.Supervisor, Wallaby.Supervisor, #PID<0.1144.0>]
2018-03-13 09:51:55.696 [error] Child Wallaby.ServerPool of Supervisor Wallaby.Driver.Supervisor failed to start
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, {:crashed, 1}}
        (poolboy) src/poolboy.erl:275: :poolboy.new_worker/1
        (poolboy) src/poolboy.erl:296: :poolboy.prepopulate/3
        (poolboy) src/poolboy.erl:145: :poolboy.init/3
        (stdlib) gen_server.erl:365: :gen_server.init_it/2
        (stdlib) gen_server.erl:333: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Start Call: :poolboy.start_link([name: {:local, Wallaby.ServerPool}, worker_module: Wallaby.Phantom.Server, size: 8, max_overflow: 0], [])
2018-03-13 09:51:55.696 [error] Child Wallaby.Phantom.Server of Supervisor #PID<0.1149.0> (:poolboy_sup) terminated
** (exit) {:crashed, 1}
Pid: #PID<0.1150.0>
Start Call: Wallaby.Phantom.Server.start_link/?
2018-03-13 09:51:55.697 [error] Child Wallaby.Phantom of Supervisor Wallaby.Supervisor failed to start
** (exit) shutdown: failed to start child: Wallaby.ServerPool
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:crashed, 1}}
            (poolboy) src/poolboy.erl:275: :poolboy.new_worker/1
            (poolboy) src/poolboy.erl:296: :poolboy.prepopulate/3
            (poolboy) src/poolboy.erl:145: :poolboy.init/3
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Start Call: Wallaby.Phantom.start_link([name: Wallaby.Driver.Supervisor])
** (Mix) Could not start application wallaby: Wallaby.start(:normal, []) returned an error: shutdown: failed to start child: Wallaby.Phantom
    ** (EXIT) shutdown: failed to start child: Wallaby.ServerPool
        ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: {:error, {:crashed, 1}}
                (poolboy) src/poolboy.erl:275: :poolboy.new_worker/1
                (poolboy) src/poolboy.erl:296: :poolboy.prepopulate/3
                (poolboy) src/poolboy.erl:145: :poolboy.init/3
                (stdlib) gen_server.erl:365: :gen_server.init_it/2
                (stdlib) gen_server.erl:333: :gen_server.init_it/6
                (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
2018-03-13 09:51:55.705 [error] GenServer #PID<0.1149.0> terminating
** (MatchError) no match of right hand side value: {:error, {:crashed, 1}}
    (poolboy) src/poolboy.erl:275: :poolboy.new_worker/1
    (poolboy) src/poolboy.erl:296: :poolboy.prepopulate/3
    (poolboy) src/poolboy.erl:145: :poolboy.init/3
    (stdlib) gen_server.erl:365: :gen_server.init_it/2
    (stdlib) gen_server.erl:333: :gen_server.init_it/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.1148.0>, {{:badmatch, {:error, {:crashed, 1}}}, [{:poolboy, :new_worker, 1, [file: 'src/poolboy.erl', line: 275]}, {:poolboy,:prepopulate, 3, [file: 'src/poolboy.erl', line: 296]}, {:poolboy, :init, 3, [file: 'src/poolboy.erl', line: 145]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 365]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 333]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
2018-03-13 09:51:55.705 [error] Process #PID<0.1149.0> terminating
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, {:crashed, 1}}
        (poolboy) src/poolboy.erl:275: :poolboy.new_worker/1
        (poolboy) src/poolboy.erl:296: :poolboy.prepopulate/3
        (poolboy) src/poolboy.erl:145: :poolboy.init/3
        (stdlib) gen_server.erl:365: :gen_server.init_it/2
        (stdlib) gen_server.erl:333: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
    (stdlib) gen_server.erl:410: :gen_server.decode_msg/9
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Initial Call: :supervisor.poolboy_sup/1
Ancestors: [Wallaby.ServerPool, Wallaby.Driver.Supervisor, Wallaby.Supervisor, #PID<0.1144.0>]
2018-03-13 09:51:55.706 [error] Process #PID<0.1143.0> terminating
** (exit) exited in: Wallaby.start(:normal, [])
    ** (EXIT) shutdown: failed to start child: Wallaby.Phantom
        ** (EXIT) shutdown: failed to start child: Wallaby.ServerPool
            ** (EXIT) an exception was raised:
                ** (MatchError) no match of right hand side value: {:error, {:crashed, 1}}
                    (poolboy) src/poolboy.erl:275: :poolboy.new_worker/1
                    (poolboy) src/poolboy.erl:296: :poolboy.prepopulate/3
                    (poolboy) src/poolboy.erl:145: :poolboy.init/3
                    (stdlib) gen_server.erl:365: :gen_server.init_it/2
                    (stdlib) gen_server.erl:333: :gen_server.init_it/6
                    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
    (kernel) application_master.erl:134: :application_master.init/4
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Initial Call: :application_master.init/4
Ancestors: [#PID<0.1142.0>]
```

**Comment by elbow-jason** [comment] 2018-03-13 16:58
Additionally, here are my versions via bash and CLI:
```
bash-3.2$ which erl
/usr/local/bin/erl
bash-3.2$ erl -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V9.0  (abort with ^G)
1>
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^Cbash-3.2$ which elixir
/Users/elbow-jason/.asdf/shims/elixir
bash-3.2$ elixir --version
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.2
bash-3.2$ which node/Users/elbow-jason/.asdf/shims/node
bash-3.2$ node --version
v8.7.0
bash-3.2$ which phantom
bash-3.2$ which phantomjs
/usr/local/bin/phantomjs
bash-3.2$ phantomjs -v
2.1.1
bash-3.2$
```

**Comment by PragTob** [comment] 2018-03-13 19:07
Some package managers split up the erlang vm weirdly and relatively standard parts might be missing... so that might be one avenue. I never noticed it with wallaby though... would be interesting which modules the apply in `(stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3` - in general I'm not so good with debugging the whole supervision trees someone else might be better :)

**Comment by keathley** [comment] 2018-03-13 20:05
@elbow-jason can you check the permissions for phantomjs?

**Comment by keathley** [comment] 2018-07-11 13:37
I'm not sure if I have anything else to go on so I'm going to close this issue for now. Feel free to re-open if you have any new insights into this problem.

**Closed by keathley** 2018-07-11 13:37 UTC

**Comment by danbee** [comment] 2018-08-06 23:46
I'm seeing the same errors consistently trying to build my app on Codeship Pro. This is a dockerized environment and I'm building the Elixir image from the `elixir:1.6.6-alpine` base image.

I'm happy to post my Dockerfile and other relevant configuration if it will help?

```
23:45:23.021 [error] GenServer #PID<0.6180.0> terminating
** (MatchError) no match of right hand side value: {:error, {:wallaby, {{:shutdown, {:failed_to_start_child, Wallaby.Phantom, {:shutdown, {:failed_to_start_child, Wallaby.ServerPool, {{:badmatch, {:error, {:timeout, {Task, :await, [%Task{owner: #PID<0.6500.0>, pid: #PID<0.6502.0>, ref: #Reference<0.336462478.1595146241.11046>}, 5000]}}}}, [{:poolboy, :new_worker, 1, [file: 'src/poolboy.erl', line: 275]}, {:poolboy, :prepopulate, 3, [file: 'src/poolboy.erl', line: 296]}, {:poolboy, :init, 3, [file: 'src/poolboy.erl', line: 145]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 365]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 333]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}}}}, {Wallaby, :start, [:normal, []]}}}}
    test/test_helper.exs:1: (file)
    (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
    (elixir) src/elixir_lexical.erl:18: :elixir_lexical.run/3
    (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
    (elixir) lib/code.ex:677: Code.require_file/2
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
    (mix) lib/mix/tasks/test.ex:256: Mix.Tasks.Test.run/1
Last message: {:EXIT, #PID<0.74.0>, {%MatchError{term: {:error, {:wallaby, {{:shutdown, {:failed_to_start_child, Wallaby.Phantom, {:shutdown, {:failed_to_start_child, Wallaby.ServerPool, {{:badmatch, {:error, {:timeout, {Task, :await, [%Task{owner: #PID<0.6500.0>, pid: #PID<0.6502.0>, ref: #Reference<0.336462478.1595146241.11046>}, 5000]}}}}, [{:poolboy, :new_worker, 1, [file: 'src/poolboy.erl', line: 275]}, {:poolboy, :prepopulate, 3, [file: 'src/poolboy.erl', line: 296]}, {:poolboy, :init, 3, [file: 'src/poolboy.erl', line: 145]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 365]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 333]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}}}}, {Wallaby, :start, [:normal, []]}}}}}, [{:elixir_compiler_130, :__FILE__, 1, [file: 'test/test_helper.exs', line: 1]}, {:elixir_compiler, :dispatch, 6, [file: 'src/elixir_compiler.erl', line: 85]}, {:elixir_lexical, :run, 3, [file: 'src/elixir_lexical.erl', line: 18]}, {:elixir_compiler, :quoted, 3, [file: 'src/elixir_compiler.erl', line: 27]}, {Code, :require_file, 2, [file: 'lib/code.ex', line: 677]}, {Enum, :"-each/2-lists^foreach/1-0-", 2, [file: 'lib/enum.ex', line: 737]}, {Enum, :each, 2, [file: 'lib/enum.ex', line: 737]}, {Mix.Tasks.Test, :run, 1, [file: 'lib/mix/tasks/test.ex', line: 256]}]}}
```

**Comment by marcelolebre** [comment] 2019-02-13 12:17
Having the same issue with GitLab CI

**Comment by keathley** [comment] 2019-02-13 14:45
@marcelolebre are you also using the phantom driver with the same elixir versions?

**Comment by marcelolebre** [comment] 2019-02-13 14:46
Elixir 1.8

**Comment by keathley** [comment] 2019-02-13 14:48
What erlang version?

**Comment by marcelolebre** [comment] 2019-02-13 14:49
21

**Comment by keathley** [comment] 2019-02-13 14:53
Cool thanks. I'm working on trying to figure out the root cause of this. We're in the middle of deprecating the phantom driver and moving towards using chrome driver as the default. I realize that's not an ideal solution to this but in the meantime that might be the best way forward.

**Comment by marcelolebre** [comment] 2019-02-13 14:56
Yeah I also tried with the chromedriver but no luck under the same conditions:
```

{:error, {:wallaby, {:bad_return, {{Wallaby, :start, [:normal, []]}, {:EXIT, {%Protocol.UndefinedError{description: "", protocol: Enumerable, value: nil}, [{Enumerable, :impl_for!, 1, [file: '/usr/local/src/elixir/lib/elixir/lib/enum.ex', line: 1]}, {Enumerable, :slice, 1, [file: '/usr/local/src/elixir/lib/elixir/lib/enum.ex', line: 193]}, {Enum, :backwards_compatible_slice, 1, [file: 'lib/enum.ex', line: 2871]}, {Enum, :slice_any, 3, [file: 'lib/enum.ex', line: 3075]}, {Enum, :at, 3, [file: 'lib/enum.ex', line: 381]}, {Wallaby.Experimental.Chrome, :validate, 0, [file: 'lib/wallaby/experimental/chrome.ex', line: 36]}, {Wallaby, :start, 2, [file: 'lib/wallaby.ex', line: 27]}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 277]}]}}}}}}
```

**Comment by keathley** [comment] 2019-02-13 15:04
Alright so it looks like there are a few things that can go wrong here with starting phantom. Most of them have to do with creating temporary directories for storing phantom state in and those sorts of things. Its just a hypothesis but it may be that running in these environments limits wallaby's ability to set up this environment correctly. If we can find a way to reproduce this locally that would be a huge win towards debugging the specific problem.

**Comment by keathley** [comment] 2019-02-13 15:07
For the specific issue with Chromedriver it looks like we're failing inside of our version check. That might indicate that the format for the chrome driver output has changed and our regex needs to be updated, or some other issue is occurring. The relevant lines are here: https://github.com/keathley/wallaby/blob/master/lib/wallaby/experimental/chrome.ex#L36

**Comment by tjshipe** [comment] 2019-03-20 13:39
As of yesterday all of my CircleCi builds started failing on Wallaby. I think it has something to do with Circle upgrading to the new versioning of Chromedriver.

```** (MatchError) no match of right hand side value: {:error, {:wallaby, {:bad_return, {{Wallaby, :start, [:normal, []]}, {:EXIT, {%Protocol.UndefinedError{description: "", protocol: Enumerable, value: nil}, [{Enumerable, :impl_for!, 1, [file: 'lib/enum.ex', line: 1]}, {Enumerable, :slice, 1, [file: 'lib/enum.ex', line: 193]}, {Enum, :backwards_compatible_slice, 1, [file: 'lib/enum.ex', line: 2871]}, {Enum, :slice_any, 3, [file: 'lib/enum.ex', line: 3075]}, {Enum, :at, 3, [file: 'lib/enum.ex', line: 381]}, {Wallaby.Experimental.Chrome, :validate, 0, [file: 'lib/wallaby/experimental/chrome.ex', line: 36]}, {Wallaby, :start, 2, [file: 'lib/wallaby.ex', line: 27]}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 277]}]}}}}}}
    test/test_helper.exs:1: (file)
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
Exited with code 1```

**Comment by mhanberg** [comment] 2019-03-20 13:41
This may have to do with chromedriver switching it version system to match chromes (2.xx -> 73.xxxxxxxxxx).

I was going to look into it but it seems to work for me locally still so i figured it wasn't an issue.

**Comment by tjshipe** [comment] 2019-03-20 13:45
Yeah I think you're on to something. It still works for me locally as well. It's only failing in CI for me.

**Comment by michallepicki** [comment] 2019-03-20 13:58
Just for reference let me note this: I can see you've opened a new issue - let's continue the discussion there:
https://github.com/keathley/wallaby/issues/419
