### ISSUE TITLE
Session ID is nil after creating session

### ISSUE THREAD

**Issue by mschae** [keathley/wallaby#386] opened 2018-08-16 16:07 UTC
To preface: We are trying to use Wallaby inside a docker container, talking to selenium in a different container.

## Issue

When invoking `Wallaby.start_session/2` it returns `nil` for the session ID.

## Test Code & HTML

`config/test.exs`:
```Elixir
config :wallaby,
  base_url: "http://backend:4001",
  driver: Wallaby.Experimental.Selenium
```

`test/support/integration_test.ex`:
```Elixir
# ...
    {:ok, session} =
      Wallaby.start_session(remote_url: "http://selenium_chrome:4444/wd/hub/")
      |> IO.inspect()
# ...
```

Result:
```
{:ok, 
  %Wallaby.Session{
    driver: Wallaby.Experimental.Selenium,
    id: nil, 
    screenshots: [],
    server: :none,
    session_url: "http://selenium_chrome:4444/wd/hub/s
ession/",
    url: "http://selenium_chrome:4444/wd/hub/session/"
}}
```

I logged the response of the selenium server and it is as follows:
```
%{
  "status" => 33,
  "value" => %{
    "error" => "session not created",
    "message" => "Unable to create session from org.openqa.selenium.remote.NewSessionPayload@3a1376aa\nBuild info: v
ersion: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'\nSystem info: host: 'b47680a9db23', ip: '192
.168.224.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.93-linuxkit-aufs', java.version: '1.8.0_171'\nDriv
er info: driver.version: unknown",
    "stackTrace" => [
      %{
        "className" => "org.openqa.selenium.remote.server.NewSessionPipeline",
        "fileName" => "NewSessionPipeline.java",
        "lineNumber" => 75,
        "methodName" => "lambda$null$4"
      },
      %{
        "className" => "java.util.Optional",
        "fileName" => "Optional.java",
        "lineNumber" => 290,
        "methodName" => "orElseThrow"
      },
      %{
        "className" => "org.openqa.selenium.remote.server.NewSessionPipeline",
        "fileName" => "NewSessionPipeline.java",
        "lineNumber" => 74,
        "methodName" => "lambda$createNewSession$5"
      },
      %{
        "className" => "java.util.Optional",
        "fileName" => "Optional.java",
        "lineNumber" => 267,
        "methodName" => "orElseGet"
      },
      %{
        "className" => "org.openqa.selenium.remote.server.NewSessionPipeline",
        "fileName" => "NewSessionPipeline.java",
        "lineNumber" => 72,
        "methodName" => "createNewSession"
      },
      %{
        "className" => "org.openqa.selenium.remote.server.commandhandler.BeginSession",
        "fileName" => "BeginSession.java",
        "lineNumber" => 65,
        "methodName" => "execute"
      },
      %{
        "className" => "org.openqa.selenium.remote.server.WebDriverServlet",
        "fileName" => "WebDriverServlet.java",
        "lineNumber" => 246,
        "methodName" => "lambda$handle$1"
      },
      %{
        "className" => "java.util.concurrent.Executors$RunnableAdapter",
        "fileName" => "Executors.java",
        "lineNumber" => 511,
        "methodName" => "call"
      },
      %{
        "className" => "java.util.concurrent.FutureTask",
        "fileName" => "FutureTask.java",
        "lineNumber" => 266,
        "methodName" => "run"
      },
      %{
        "className" => "java.util.concurrent.ThreadPoolExecutor",
        "fileName" => "ThreadPoolExecutor.java",
        "lineNumber" => 1149,
        "methodName" => "runWorker"
      },
      %{
        "className" => "java.util.concurrent.ThreadPoolExecutor$Worker",
        "fileName" => "ThreadPoolExecutor.java",
        "lineNumber" => 624,
        "methodName" => "run"
      },
      %{
        "className" => "java.lang.Thread",
        "fileName" => "Thread.java",
        "lineNumber" => 748,
        "methodName" => "run"
      }
    ],
    "stacktrace" => "org.openqa.selenium.SessionNotCreatedException: Unable to create session from org.openqa.seleni
um.remote.NewSessionPayload@3a1376aa\nBuild info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08
.936Z'\nSystem info: host: 'b47680a9db23', ip: '192.168.224.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9
.93-linuxkit-aufs', java.version: '1.8.0_171'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote
.server.NewSessionPipeline.lambda$null$4(NewSessionPipeline.java:75)\n\tat java.util.Optional.orElseThrow(Optional.j
ava:290)\n\tat org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$5(NewSessionPipeline.jav
a:74)\n\tat java.util.Optional.orElseGet(Optional.java:267)\n\tat org.openqa.selenium.remote.server.NewSessionPipeli
ne.createNewSession(NewSessionPipeline.java:72)\n\tat org.openqa.selenium.remote.server.commandhandler.BeginSession.
execute(BeginSession.java:65)\n\tat org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$1(WebDriverServ
let.java:246)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurre
nt.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.ja
va:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Threa
d.run(Thread.java:748)\n"
  }
}
```

**Comment by keathley** [comment] 2018-08-16 19:09
Looks like you're trying to drive a chrome browser. Is that correct? Do you have chromedriver installed in the selenium docker container?

**Comment by mschae** [comment] 2018-08-16 19:13
You are correct, I’m trying to remote-control Chrome via selenium. I don’t have anything installed in the app container and I’m talking to the webdriver Server in the selenium/chrome container.

It works with hound but I was trying to switch to wallaby because I saw that you are putting more effort into this project recently and hound seems stale at the moment.

**Comment by mschae** [comment] 2018-08-16 19:14
BTW I’m using the „official“ selenium chrome-standalone docker image: https://hub.docker.com/r/selenium/standalone-chrome/

**Comment by keathley** [comment] 2018-08-16 19:33
My only theory is that we're not sending the correct capabilities or something to selenium. But I'm not sure what that would be specifically. @aaronrenner knows more about selenium then I do. We should also be returning an error here if this fails. We shouldn't end up in a situation where we think a session has been created when it hasn't been.

**Comment by keathley** [comment] 2018-10-31 13:09
We've recently made some improvements to the error handling. These are in master. If you'd like to test them out that would be greatly appreciated.

**Comment by michallepicki** [comment] 2019-01-15 18:30
Hi @mschae
Did you have any progress with resolving the issue?

I just had a similar problem (`session.id` was `nil`) using the Selenium driver and in my case passing capabilities to options when starting session helped:

```
{:ok, session} = Wallaby.start_session(remote_url: "http://selenium_address:4444/wd/hub/", capabilities: %{browserName: "chrome"})
```

**Comment by keathley** [comment] 2019-01-22 15:24
@michallepicki do you know what the underlying issue was?

**Comment by michallepicki** [comment] 2019-01-22 16:46
@keathley I'm not sure, but as I said, I can easily reproduce this using both `selenium-server-standalone-3.141.59.jar` or `3.141.59-europium` docker images.

```
Wallaby.start_session(remote_url: "http://localhost:4444/wd/hub/")
  |> IO.inspect()
{:ok,
 %Wallaby.Session{
   driver: Wallaby.Experimental.Selenium,
   id: nil,
   screenshots: [],
   server: :none,
   session_url: "http://localhost:4444/wd/hub/session/",
   url: "http://localhost:4444/wd/hub/session/"
 }}
```

This doesn't happen with minimal capabilities with browser specified passed to `start_session`

```
Wallaby.start_session(remote_url: "http://selenium_address:4444/wd/hub/",
  capabilities: %{browserName: "chrome"})
  |> IO.inspect()

{:ok,
 %Wallaby.Session{
   driver: Wallaby.Experimental.Selenium,
   id: "0093d5a14244f4471428e399c172d37c",
   screenshots: [],
   server: :none,
   session_url: "http://localhost:4444/wd/hub/session/0093d5a14244f4471428e399c172d37c",
   url: "http://localhost:4444/wd/hub/session/0093d5a14244f4471428e399c172d37c"
 }}
```

**Comment by mhanberg** [comment] 2019-09-04 23:56
@michallepicki are you still able to reproduce this?

**Comment by michallepicki** [comment] 2019-09-05 06:48
@mhanberg Yes! Just start up selenium session not passing any capabilities. I think we should add default capabilities to the selenium driver. We can do it as part of #460

**Closed by michallepicki** 2019-09-05 06:48 UTC
