### ISSUE TITLE
Checkbox unselectable despite having set id and for attributes

### ISSUE THREAD

**Issue by juddey** [keathley/wallaby#461] opened 2019-08-28 04:22 UTC
Thanks to the new maintainers for giving wallaby some :heart:.

I'm using wallaby to test a reactjs SPA (elixir as backend), but its failing to find a checkbox I have created with [material-ui](https://material-ui.com/components/checkboxes/#checkboxes).

Using: 
```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]
Elixir 1.9.1 (compiled with Erlang/OTP 21)
Chromium Version 76.0.3809.100 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
```
## Test Code & HTML
The test code is quite simple 
```
    |> fill_in(Query.text_field("sessions.0.start_dt"), with: "01/08/2019")
    |> click(Query.checkbox("Mon"))
```

Results in this test failure:
```
  1) test Adds a new Centre and Room (TiakiWeb.Test.Feature.CentreTest)
     test/features/centre_test.exs:9
     ** (Wallaby.QueryError) The text 'Mon' matched a label but the label's 'for' attribute
     doesn't match the id of any element.
     
     Make sure that id on your element is `id="Mon"`.
     
     code: |> click(Query.checkbox("Mon"))
     stacktrace:
       (wallaby) lib/wallaby/browser.ex:478: Wallaby.Browser.find/2
       (wallaby) lib/wallaby/browser.ex:456: Wallaby.Browser.find/3
       test/features/centre_test.exs:34: (test)
```
Picture is worth 1000 words, so heres a screen shot of the failing test and the attributes I've added:
![image](https://user-images.githubusercontent.com/7445602/63825043-483d1a80-c9ad-11e9-888d-07391ac65fae.png)

What have I missed?

Thanks!
PS. if this is more stackoverflow material, feel free to close and will post there.

**Comment by mhanberg** [comment] 2019-08-28 22:37
@juddey I am not able to reproduce this on master. 

What version of Wallaby are you using? 

If you get the chance would you be able to provide a minimal reproduction repository that I could clone?

Thanks

**Comment by juddey** [comment] 2019-08-28 22:41
Im using version 0.22.0.  I'll give master a go and see what happens. I can do up a repo too, but that will take some time.

**Comment by mhanberg** [comment] 2019-08-28 22:42
I would try with version 0.23.0 at least (there isn't much on master that isn't on 0.23.0).

**Comment by mhanberg** [comment] 2019-09-04 23:46
@juddey I am going to close this, if you continue to see the error I will reopen.

**Closed by mhanberg** 2019-09-04 23:46 UTC

**Comment by michallepicki** [comment] 2019-09-05 06:40
@juddey as note, some js frameworks can have custom checkboxes that make the `input` element invisible with css and add their own custom visual check indicator... For this reason I sometimes had to click on the label instead
